on:
  push:
  workflow_dispatch:
name: demo workflow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

jobs:
  build:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0
    - name: Write a multi-line message
      run: |
        echo This demo file shows a 
        echo very basic and easy-to-understand workflow.
        cat README.md
